### PR TITLE
feat: added swagger docs

### PR DESCRIPTION
**Pull request by SreehariJayaraj**

### CODE REVIEW

**Comment by SreehariJayaraj** [comment]
can you check  this  pr #9  @abhi-shek-raj

**Comment by chauhan17nitin** [comment]
Hi @sreehari2003, 

few things i think we should add, 

1. add in readme how devs can start using it (swag init and other stuff (installation and generating doc just via a command))
2. integrating swagger doc with healthcheck api atleast (/api/ping in this)
3. giving url in readme, which will show documentation (/docs/index.html in this case)

**Comment by uzaxirr** [comment]
Hey @sreehari2003 still working on this?

**Comment by SreehariJayaraj** [comment]
> Hey @sreehari2003 still working on this?

I am having my semester exam right now so i won't be able to work on this for few weeks, you can un assign me @uzaxirr

**Pull request closed without merging**
