### PR TITLE
Documentation for cloud storage function

### LINKED ISSUE #47: Document setting up Cloud Storage
**Is your feature request related to a problem? Please describe.**
Documentation

**Describe the solution you'd like**
As now we have function to upload the folder directly, there should be a doc when people can read and easily understand, how to setup GCP/Azure/AWS.

### PR DESCRIPTION
**Pull request by Shofiya2003**
Added documentation for cloud storage function including details to configure cloud storage accounts. 
Closes #47

### CODE REVIEW

**Comment by Shofiya2003** [comment]
https://github.com/ZeStream/zestream-server/blob/038f95166edeb29ac74e3d1d743f810081c050bc/service/consumer.go#L87
Here, we are storing the Azure container name in constants. Shouldn't we use an env variable for it?
@abhishekraj272 @uzaxirr

**Comment by uzaxirr** [comment]
No, Container name isn't some security key or any much confidential info which could be used to gain access. Such things should be stored in constants i believe.

**Comment by Shofiya2003** [comment]
Right. But does the user set the container name (or it stays the same for every user) or they just provide the credentials? @uzaxirr

**Comment by uzaxirr** [comment]
> Right. But does the user set the container name (or it stays the same for every user) or they just provide the credentials? @uzaxirr

It's customisable, currently it stays the same (the value mentioned in constant) but if someone wants to change for their self-hosted instance they can do so by editing the constant's value in their fork

**Comment by Shofiya2003** [comment]
Alrighty. Then we should not create it as an `env` variable. Thank you for the explanation.
 https://github.com/ZeStream/zestream-server/blob/038f95166edeb29ac74e3d1d743f810081c050bc/configs/configs.go#L34
 Shouldn't we have the s3 bucket name and region as constants too?

**Comment by abskrj** [comment]
@Shofiya2003 bucket name and region should be configurable from user side, cos bucket name is unique and people can deploy it on any region so, should be set by user only. 

Container inside the bucket is generated by the code and can be common on every bucket. Container is just a folder inside the bucket.

**Comment by Shofiya2003** [comment]
Okay
Do you want me to make any changes to the doc? 
@abhishekraj272 @uzaxirr

**Review by uzaxirr — APPROVED** [review]
LGTM!
This is a good starting point. We can improve and iterate over it later on as well

**Pull request merged**
